version: '3'

services:
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sql_migrations
    ports:
      - "3306:3306"
  postgresql:
    image: postgres:9.6
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sql_migrations
    ports:
      - "5432:5432"
